### ISSUE TITLE
[Remove.swift]

### ISSUE THREAD

**Issue by MrDevel0per** [OCA-Creations/Ally#9]
Improve file.
# TODOs
- [ ] Improve docs for options
- [ ] Improve bold printing
- [ ] Improve `CommandConfiguration`
- [ ] Document `run` function
- [ ] Rewrite, secularize, and improve the `scanAndRemoveIfNeeded` function
- [ ] Fix Prefer For-Where Violation: `where` clauses are preferred over a single `if` inside a `for` (for_where)
- [ ] Document function
